### PR TITLE
Drop 3.5 and support 3.7

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by seisman** [comment]
@leouieda This PR is ready for review.

**Comment by leouieda** [comment]
The build is complaining about not finding `HI_geoid_02.nc` on the remote server. That's weird. I'm getting similar errors on `gmt which HI_geoid_02.nc -Gc` locally but the Mac builds seem fine.

**Comment by seisman** [comment]
I don't see any errors in my Linux and macOS.
```
$ gmt --version
5.4.5

$ gmt which @HI_geoid_02.nc -Gc -Vd
gmt: GMT->session.HOMEDIR = /mnt/home/tiandong
gmt: GMT->session.USERDIR = /mnt/home/tiandong/.gmt [created]
gmt: GMT->session.CACHEDIR = /mnt/home/tiandong/.gmt/cache [created]
gmt: GMT: 1. gmt_getsharepath trying current dir
gmt: GMT: 2. gmt_getsharepath trying USERDIR /mnt/home/tiandong/.gmt
gmt: GMT: 3. gmt_getsharepath trying USERDIR subdir /mnt/home/tiandong/.gmt/postscriptlight
gmt: GMT: 4. gmt_getsharepath trying SHAREDIR subdir /opt/local/GMT/5.4.5/share/postscriptlight
gmt: Map distance calculation will be Cartesian
gmt: The PROJ_GEODESIC set to Vincenty
gmt: GMT_Create_Session initialized GMT structure
gmt: Shared Library # 0 (core). Path = libgmt.so
gmt: Loading core GMT shared library: libgmt.so
gmt: Loading GMT plugins from: /opt/local/GMT/5.4.5/lib64/gmt/plugins
gmt: Shared Library # 1 (supplements). Path = /opt/local/GMT/5.4.5/lib64/gmt/plugins/supplements.so
gmtwhich: api_init_export: Passed family = Text Table and geometry = Non-Geographical
gmtwhich: Object ID 0 : Registered Text Table Stream 2ab520c2a400 as an Output resource with geometry Non-Geographical [n_objects = 1]
gmtwhich: api_init_export: Added stdout to registered destinations
gmtwhich: GMT_Init_IO: Returned first Output object ID = 0
gmtwhich: GMT_Begin_IO: Initialize record-by-record access for Output
gmtwhich: api_next_io_source: Selected object 0
gmtwhich: Writing Text Table to Standard Output stream
gmtwhich: GMT_Begin_IO: Output resource access is now enabled [record-by-record]
gmtwhich: Downloading file ftp://ftp.soest.hawaii.edu/gmt/data/cache/HI_geoid_02.nc ...
gmtwhich: Download complete [Got 464.538 kb].
/mnt/home/tiandong/.gmt/cache/HI_geoid_02.nc
gmtwhich: GMT_End_IO: Output resource access is now disabled
gmtwhich: gmtapi_unregister_io: Unregistering object no 0 [n_objects = 0]
gmtwhich (gmtlib_free_tmp_arrays): tried to free unallocated memory
gmt: Entering GMT_Destroy_Session
```

**Comment by seisman** [comment]
Can we ignore the "remote file" issue and merge this PR? The build failures are not caused by this sphinx extension.

**Comment by leouieda** [comment]
Sure

**Pull request merged**
